### ISSUE TITLE
Estudos

### ISSUE THREAD

**Issue by alexsandermviana** [Spoiler-cmd/JavaScript-iniciante-#1]
Opa Yuri, tudo bom ?
Deixa eu te perguntar, você está aprendendo JS por onde? Estou interessado em começar a aprender também.

**Comment by Spoiler-cmd** [comment]
Olá, estou bem. Espero que esteja tudo bem com você. Estou aprendendo pela
internet mesmo. Qualquer coisa fala que te mando os links, e também podemos
estudar juntos.(se quiser claro) Boa noite

Em ter, 28 de jan de 2020 às 21:16, Alexsander Martins Viana <
notifications@github.com> escreveu:

**Comment by alexsandermviana** [comment]
Opa, tranquilo. 
Eu participo de um grupo bem ativo sobre front end. Se quiser entrar: https://chat.whatsapp.com/0vz9qD0qU9PFNG4elek48x

**Comment by Spoiler-cmd** [comment]
Entrei la e falei boa noite

Em ter, 28 de jan de 2020 às 21:38, Alexsander Martins Viana <
notifications@github.com> escreveu:

**Comment by alexsandermviana** [comment]
Obrigado por entrar no grupo Yuri. 
É uma das pessoas mais ativas e esforçadas de lá.
Você tem um diferencial muito forte que é sua grande simpática e comunicação. 😄

**Comment by Spoiler-cmd** [comment]
Oopa mano, muito obrigado. É uma honra participar desse grupo. Vlw

Em sáb, 8 de fev de 2020 às 22:52, Alexsander Martins Viana <
notifications@github.com> escreveu:
